class Aleutian < Formula
  desc "Aleutian Local: MLOps Control Plane for LLM Apps"
  homepage "https://github.com/jinterlante1206/AleutianLocal"
  # URL points to the source code tarball generated by GitHub for the specific release tag.
  # !! IMPORTANT !!: You MUST update the 'url' and 'sha256' for EVERY new release.
  url "https://github.com/jinterlante1206/AleutianLocal/archive/refs/tags/v0.1.5.tar.gz"
  sha256 "5cdb3056aae490ca77713f14e2bf93253736898c8dd21463fdbd8e02bc37c901"
  license "AGPL-3.0-only"

  # We need Go to build the binary
  depends_on "go" => :build
  depends_on "podman"
  depends_on "podman-compose"

  def install
    ldflags = "-s -w -X main.version=#{version}"
    system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/aleutian"
  end

  test do
    assert_match "aleutian version #{version}", shell_output("#{bin}/aleutian --version")
  end
end
