class Aleutian < Formula
  desc "Aleutian Local: MLOps Control Plane for LLM Apps"
  homepage "https://github.com/jinterlante1206/AleutianLocal"
  # URL points to the source code tarball generated by GitHub for the specific release tag.
  # !! IMPORTANT !!: You MUST update the 'url' and 'sha256' for EVERY new release.
  # curl -L "https://github.com/jinterlante1206/AleutianLocal/archive/refs/tags/v0.4.1.tar.gz" | shasum -a 256
  url "https://github.com/jinterlante1206/AleutianLocal/archive/refs/tags/v0.4.1.tar.gz"
  sha256 "4977b11dc5373122d320c3e4e1aebca703e045091a6d8b97595b3f82296225b3"
  license "AGPL-3.0-only"

  # We need Go to build the binary
  depends_on "go" => :build
  depends_on "podman"
  depends_on "podman-compose"


  def install
    ldflags = "-s -w -X main.version=#{version}"
    system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/aleutian"
  end

  def caveats
    <<~EOS
      Aleutian has been successfully installed, but it requires the 'ollama' Cask.
      Please install it manually by running:

        brew install --cask ollama
    EOS
  end

  test do
    assert_match "aleutian version #{version}", shell_output("#{bin}/aleutian --version")
  end
end
