class Aleutian < Formula
  desc "Aleutian Local: MLOps Control Plane for LLM Apps"
  homepage "https://github.com/jinterlante1206/AleutianLocal"
  # URL points to the source code tarball generated by GitHub for the specific release tag.
  # !! IMPORTANT !!: You MUST update the 'url' and 'sha256' for EVERY new release.
  url "https://github.com/jinterlante1206/AleutianLocal/archive/refs/tags/v0.1.0.tar.gz" # <-- EXAMPLE version, replace
  sha256 "69e31133d97343bb8880269ac30b3c5163bd8440e5dc8694df5723552fa9b755"                                     # <-- EXAMPLE checksum, replace
  license "AGPL-3.0-only"

  # We need Go to build the binary
  depends_on "go" => :build
  depends_on "podman"
  depends_on "podman-compose"

  def install
    ldflags = "-s -w -X main.version=#{version}"
    system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/aleutian"
  end

  test do
    assert_match "aleutian version #{version}", shell_output("#{bin}/aleutian --version")
  end
end
